### ISSUE TITLE
Duck jump should work at crouch speed instead of only at zero velocity

### ISSUE THREAD

**Issue by GunnarKafel** [Facepunch/sbox-platformer#14]
Right now the duck jump feels unnatural to use since I have to wait to slow to a stop. This often leads to doing a normal jump instead of the duck jump. I feel that it would be a bit more responsive if it worked at slower speeds.

**Comment by bakscratch** [comment]
Just uploaded something like this I think, let me know :)

**Comment by GunnarKafel** [comment]
Works great ty
